
# services:

#   db:
#     image: postgres:16-alpine
#     container_name: predictor_db
#     restart: always
#     env_file: .env
#     environment:
#       POSTGRES_DB: ${POSTGRES_DB}
#       POSTGRES_USER: ${POSTGRES_USER}
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#     volumes:
#       - ./postgres_data:/var/lib/postgresql/data
#       - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
#     networks:
#       - backend
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
#       interval: 10s
#       timeout: 5s
#       retries: 5

#   app:
#       build: 
#         context: .
#         dockerfile: Dockerfile
#       container_name: predictor_app
#       restart: always
#       env_file: .env
#       environment:
#         DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
#         OAUTH_CLIENT_ID: ${OAUTH_CLIENT_ID}
#         OAUTH_CLIENT_SECRET: ${OAUTH_CLIENT_SECRET}
#         OAUTH_REDIRECT_URI: ${OAUTH_REDIRECT_URI}
#         APP_SECRET_KEY: ${APP_SECRET_KEY}
#       depends_on:
#         db:
#           condition: service_healthy
#       ports:
#         - "8080:8080"
#       healthcheck:
#         test: ["CMD-SHELL", "curl -f https://sq.clubs.codam.nl || exit 1"]
#         interval: 5s
#         timeout: 3s
#         retries: 10
#         start_period: 10s
#       networks:
#         - backend
#  #       - frontend

#  # nginx:
#  #     image: nginx:1.25-alpine
#  #     container_name: predictor_nginx
#  #     restart: always
#  #     ports:
#  #       - "8000:80"
#  #       - "443:443"
#  #     volumes:
#  #       - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#  #       - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
#  #       - ./nginx/certs/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt:ro
#  #       - ./nginx/certs/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key:ro
#  #     depends_on:
#  #       app: 
#  #         condition: service_healthy  # waits for app to be ready
#  #     networks:
#  #       - frontend
#  # certbot:
#  #     image: certbot/certbot
#  #     volumes:
#  #       - ./certbot/conf:/etc/letsencrypt
#  #       - ./certbot/www:/var/www/certbot
# volumes:
#   postgres_data:

# networks:
#   backend:   # app <-> db  (nginx cannot reach db)
#   frontend:  # nginx <-> app





# old one
services:

  db:
    image: postgres:16-alpine
    container_name: predictor_db
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
      build: 
        context: .
        dockerfile: Dockerfile
      container_name: predictor_app
      restart: always
      env_file: .env
      environment:
        DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
        OAUTH_CLIENT_ID: ${OAUTH_CLIENT_ID}
        OAUTH_CLIENT_SECRET: ${OAUTH_CLIENT_SECRET}
        OAUTH_REDIRECT_URI: ${OAUTH_REDIRECT_URI}
        APP_SECRET_KEY: ${APP_SECRET_KEY}
      depends_on:
        db:
          condition: service_healthy
      healthcheck:
        test: ["CMD-SHELL", "curl -f http://localhost:8080/ || exit 1"]
        interval: 5s
        timeout: 3s
        retries: 10
        start_period: 10s
      networks:
        - backend
        - frontend

  nginx:
      image: nginx:1.25-alpine
      container_name: predictor_nginx
      restart: always
      ports:
        - "8000:80"
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        app:
          condition: service_healthy  # waits for app to be ready
      networks:
        - frontend

volumes:
  postgres_data:

networks:
  backend:   # app <-> db  (nginx cannot reach db)
  frontend:  # nginx <-> app
